### ISSUE TITLE
Improve events management

### ISSUE THREAD

**Issue by pablocrivella** [MustardSeed/Fraternos#93]
### Tasks

- [x] Add name to events
- [x] Allow editing events
- [x] Allow deleting events
- [x] Show all events on calendar (not just upcoming)
