### ISSUE TITLE
Hide unauthorized actions

### ISSUE THREAD

**Issue by pablocrivella** [MustardSeed/Fraternos#97]
### Tasks

- [ ] Hide "Add member" button
- [ ] Hide "New event" button
- [ ] Hide "Random generator" button
